# These are supported funding model platforms

github: [mikaleb]
patreon: mikaleb
# open_collective: hidepuretech
ko_fi: mikaleb
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Mikaleb
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: mikaleb
buy_me_a_coffee: mikaleb
thanks_dev: mikaleb
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
